[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "sollol"
version = "0.3.0"
description = "Super Ollama Load Balancer with Intelligent Routing and Distributed Inference"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "BenevolentJoker-JohnL", email = "benevolentjoker@gmail.com"}
]
keywords = ["ai", "llm", "distributed", "ollama", "load-balancing", "inference", "llama-cpp"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: System :: Distributed Computing",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "requests>=2.31.0",
    "httpx>=0.24.0",
    "ipaddress>=1.0.23",
    "dask[distributed]>=2024.1.0",
    "rich>=13.7.0",
    "flask>=2.0.0",
    "flask-cors>=4.0.0",
    "flask-sock>=0.7.0",
    "waitress>=3.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.0.0",
    "mypy>=1.0.0",
]

[project.urls]
Homepage = "https://github.com/BenevolentJoker-JohnL/SynapticLlamas"
Documentation = "https://github.com/BenevolentJoker-JohnL/SynapticLlamas/blob/main/README.md"
Repository = "https://github.com/BenevolentJoker-JohnL/SynapticLlamas"
"Bug Tracker" = "https://github.com/BenevolentJoker-JohnL/SynapticLlamas/issues"

[project.scripts]
sollol = "sollol.cli:main"

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
